---
admin_user: user

timezone: "UTC"

cluster_hosts:
  - ip: "172.16.0.11"
    name: "k8s-master-01"
  - ip: "172.16.0.12"
    name: "k8s-worker-01"
  - ip: "172.16.0.13"
    name: "k8s-worker-02"
  - ip: "172.16.0.20"
    name: "haproxy-01"
  - ip: "172.16.0.30"
    name: "nfs-01"
  - ip: "172.16.0.40"
    name: "nexus-01"
