---
- name: Check if Helm is already installed
  ansible.builtin.command: helm version --short
  register: helm_check
  changed_when: false
  failed_when: false

- name: Download Helm install script
  ansible.builtin.get_url:
    url: "{{ helm_install_script_url }}"
    dest: "{{ helm_install_script_path }}"
    mode: "0755"
  when: helm_check.rc != 0
  become: true

- name: Install Helm
  ansible.builtin.command: "{{ helm_install_script_path }}"
  when: helm_check.rc != 0
  become: true

- name: Verify Helm installation
  ansible.builtin.command: helm version --short
  register: helm_version
  changed_when: false

- name: Display Helm version
  ansible.builtin.debug:
    var: helm_version.stdout
