---
calico_version: "v3.29.7"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"

calico_manifest_path: "/tmp/calico-{{ calico_version }}.yaml"
calico_namespace: "kube-system"

calico_recover_broken_install: false
