---
- name: Configure NFS server
  hosts: nfs
  gather_facts: true

  roles:
    - nfs_server

- name: Configure NFS clients on Kubernetes nodes
  hosts: k8s_cluster
  gather_facts: true

  roles:
    - nfs_clients

- name: Verify files created on NFS server
  hosts: nfs
  gather_facts: false

  tasks:
    - name: List NFS test files
      ansible.builtin.command: ls -lah /srv/nfs/k8s
      register: nfs_test_files
      changed_when: false
      become: true

    - name: Display NFS test files
      ansible.builtin.debug:
        var: nfs_test_files.stdout_lines
